name: Test Build
description: Lint, Build, Test
inputs:
  directory:
    description: "Working directory"
    required: true
    default: "./"
runs:
  using: "composite"
  steps:
    - uses: ./.github/steps/install
      with:
        directory: ${{inputs.directory}}

    - run: yarn test:coverage
      shell: bash
      working-directory: ${{inputs.directory}}

    - name: Read coverage text report
      uses: fingerprintjs/action-coverage-report-md@v1
      id: coverage-md
      with:
        textReportPath: ${{inputs.directory}}/coverage/coverage.txt
        srcBasePath: ${{inputs.directory}}/src

    - uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: ${{inputs.directory}}
        message: |
          <details>
            <summary>Show coverage report for ${{inputs.directory}}</summary>

            ${{ steps.coverage-md.outputs.markdownReport }}
          </details>
