name: Build App
description: Build web app
inputs:
  directory:
    description: "Working directory"
    required: true
    default: "./"
runs:
  using: "composite"
  steps:
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ${{inputs.directory}}/**/node_modules
          !**/dist/node_modules
        key: nodemodules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: nodemodules-

    - name: Install Node packages
      run: yarn install
      shell: bash
      working-directory: ${{inputs.directory}}

    - name: Build
      run: yarn build:prod
      shell: bash
      working-directory: ${{inputs.directory}}
