name: Build App
description: Build web app
inputs:
  directory:
    description: "Working directory"
    required: true
    default: "./"
runs:
  using: "composite"
  steps:
    - uses: ./.github/steps/install
      with:
        directory: ${{inputs.directory}}

    - name: Build
      run: yarn build:prod
      shell: bash
      working-directory: ${{inputs.directory}}
