name: Release
description: Release
inputs:
  directory:
    description: "Working directory"
    required: true
    default: "./"
  release-token:
    description: "Github token for release"
    required: true
  npm-token:
    description: "NPM token for release"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: yarn install
      shell: bash
      working-directory: ${{inputs.directory}}

    - name: Build library
      run: yarn build
      shell: bash
      working-directory: ${{inputs.directory}}

    - name: Release
      run: yarn release
      shell: bash
      working-directory: ${{inputs.directory}}
      env:
        GITHUB_TOKEN: ${{ inputs.release-token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
        HUSKY: "0"
