name: Generate web app, docs and coverage report
on:
  push:
    branches:
      - main
    paths:
      - core/**
      - app/**
jobs:
  generate-docs-and-coverage-core:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/steps/docs-coverage-report
        with:
          directory: core
      - uses: ./.github/steps/build-app
        with:
          directory: app
      - name: Prepare folder for gh-pages
        run: |
          mv app/dist gh-pages
          mv core/gh-pages ./gh-pages/core
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: gh-pages
