name: Pull requests Check
on:
  pull_request:
jobs:
  lint-test:
    name: Lint, build and test
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            core:
              - 'sqc-core-functions/**'
            ui:
              - 'sqc-ui-components/**'

      - if: steps.changes.outputs.core == 'true'
        uses: ./.github/steps/test
        with:
          directory: sqc-core-functions
      - if: steps.changes.outputs.ui == 'true'
        uses: ./.github/steps/test
        with:
          directory: sqc-ui-components

  test-coverage:
    name: Run tests & check coverage
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read # for private repos
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            core:
              - 'sqc-core-functions/**'
            ui:
              - 'sqc-ui-components/**'

      - if: steps.changes.outputs.core == 'true'
        uses: ./.github/steps/test-coverage
        with:
          directory: sqc-core-functions
      - if: steps.changes.outputs.ui == 'true'
        uses: ./.github/steps/test-coverage
        with:
          directory: sqc-ui-components

  chromatic:
    name: Run Chromatic publish for UI review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 # suggested by Chromatic
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            ui:
              - 'sqc-ui-components/**'

      - if: steps.changes.outputs.ui == 'true'
        uses: ./.github/steps/install
        with:
          directory: sqc-ui-components

      - if: steps.changes.outputs.ui == 'true'
        name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: sqc-ui-components
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
